name: Playwright Tests to AWS
on:
  # Trigger the workflow on push or pull request
  # or by manually running it from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      # Use the Playwright image
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
  # Provision and deploy the report site with Terraform
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: report
      url: ${{ steps.deploy.outputs.deployment_url }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4.1.7
      with:
        name: playwright-report
        path: playwright-report/
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Initialize Terraform
      working-directory: ./aws
      run: terraform init
    - name: Deploy the report site
      working-directory: ./aws
      id: deploy
      run: |
        terraform apply -auto-approve
        echo "deployment_url=https://$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT
        echo "distribution_id=$(terraform output -raw cloudfront_dist_id)" >> $GITHUB_OUTPUT
    # Invalidate the CloudFront cache to make sure the latest report is served
    - name: Invalidate CloudFront cache
      if: always()
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ steps.deploy.outputs.distribution_id }} --paths "/*"