name: Playwright Tests to AWS
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  # Provision and deploy the report site with Terraform
  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: report
      url: ${{ steps.provision.outputs.deployment_url }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3
      with:
        name: playwright-report
        path: playwright-report/
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Provision the report site
      id: provision
      working-directory: ./aws
      run: |
        terraform init
        terraform apply -auto-approve
        echo "deployment_url=https://$(terraform output -raw cloudfront_domain_name)" >> $GITHUB_OUTPUT
